name = "Parameters2JSON"
uuid = "5c28a155-4156-423b-a2d5-76ca6c6310d4"
authors = ["W. Joe Meese <meese022@umn.edu> and contributors"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
StructTypes = "1"
JSON3 = "1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
